services:
  - type: web
    name: precision-tasker
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_SSLMODE
        value: require
      - key: APP_NAME
        value: Precision Tasker
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PASSWORD
        sync: false
